version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  continuation: circleci/continuation@1.0.0

parameters:
  check_files:
    type: boolean
    default: true
  run_all:
    type: boolean
    default: false

jobs:
  choose_ci_jobs:
    docker:
      - image: debian:bullseye
    resource_class: small
    steps:
      - run:
          name: Install Yarn
          command: |
            apt update
            apt install -y wget git curl jq
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt install -y nodejs
            npm install --global yarn
      - checkout
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Filter jobs
          command: |
            node ./scripts/circleci/pipeline_selection.js filter-jobs \
              -t $REACT_NATIVE_BOT_GITHUB_TOKEN \
              -s $CIRCLE_SHA1 \
              -u $CIRCLE_USERNAME
      - run:
          name: Create config
          description: Generates a configuration on the fly, depending on the files that have been modified
          command: |
            node ./scripts/circleci/pipeline_selection.js create-configs
      - continuation/continue:
            configuration_path: .circleci/generated_config.yml

# our single workflow, that triggers the setup job defined above
workflows:
  always-run:
    jobs:
      - choose_ci_jobs
